import {Font} from 'react-native-paper/lib/typescript/types';

export const fontConfig = {
  displaySmall: {
    fontFamily: 'Font',
    fontSize: 36,
    fontWeight: '400' as Font['fontWeight'],
    letterSpacing: 0,
    lineHeight: 44,
  },
  displayMedium: {
    fontFamily: 'Font',
    fontSize: 45,
    fontWeight: '400' as Font['fontWeight'],
    letterSpacing: 0,
    lineHeight: 52,
  },
  displayLarge: {
    fontFamily: 'Font',
    fontSize: 57,
    fontWeight: '400' as Font['fontWeight'],
    letterSpacing: 0,
    lineHeight: 64,
  },
  headlineSmall: {
    fontFamily: 'Font',
    fontSize: 24,
    fontWeight: '400' as Font['fontWeight'],
    letterSpacing: 0,
    lineHeight: 32,
  },
  headlineMedium: {
    fontFamily: 'Font',
    fontSize: 28,
    fontWeight: '400' as Font['fontWeight'],
    letterSpacing: 0,
    lineHeight: 36,
  },
  headlineLarge: {
    fontFamily: 'Font',
    fontSize: 32,
    fontWeight: '400' as Font['fontWeight'],
    letterSpacing: 0,
    lineHeight: 40,
  },
  titleSmall: {
    fontFamily: 'Font',
    fontSize: 14,
    fontWeight: '500' as Font['fontWeight'],
    letterSpacing: 0.1,
    lineHeight: 20,
  },
  titleMedium: {
    fontFamily: 'Font',
    fontSize: 16,
    fontWeight: '500' as Font['fontWeight'],
    letterSpacing: 0.15,
    lineHeight: 24,
  },
  titleLarge: {
    fontFamily: 'Font',
    fontSize: 22,
    fontWeight: '400' as Font['fontWeight'],
    letterSpacing: 0,
    lineHeight: 28,
  },
  labelSmall: {
    fontFamily: 'Font',
    fontSize: 11,
    fontWeight: '700' as Font['fontWeight'],
    letterSpacing: 0.5,
    lineHeight: 16,
  },
  labelMedium: {
    fontFamily: 'Font',
    fontSize: 12,
    fontWeight: '700' as Font['fontWeight'],
    letterSpacing: 0.5,
    lineHeight: 16,
  },
  labelLarge: {
    fontFamily: 'Font',
    fontSize: 14,
    fontWeight: '700' as Font['fontWeight'],
    letterSpacing: 0.1,
    lineHeight: 20,
  },
  bodySmall: {
    fontFamily: 'Font',
    fontSize: 12,
    fontWeight: '400' as Font['fontWeight'],
    letterSpacing: 0.4,
    lineHeight: 16,
  },
  bodyMedium: {
    fontFamily: 'Font',
    fontSize: 14,
    fontWeight: '400' as Font['fontWeight'],
    letterSpacing: 0.25,
    lineHeight: 20,
  },
  bodyLarge: {
    fontFamily: 'Font',
    fontSize: 16,
    fontWeight: '400' as Font['fontWeight'],
    letterSpacing: 0.15,
    lineHeight: 24,
  },
};
